version: "3.7"
services:
  webapp:
    build:
      context: .    
      dockerfile: Dockerfile
      args:
        JAR_FILE: "springapi-0.0.1-SNAPSHOT.jar"
    ports:
    - "8080:8080"

  postgresql:
    image: postgres:10.5
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"    
    