DROP TABLE IF EXISTS "categories";

CREATE TABLE "categories" (
  id SERIAL PRIMARY KEY,
  name varchar(255) default NULL,
  account varchar(255),
  mail varchar(255) default NULL
);

INSERT INTO "categories" (name,account,mail) VALUES ('Dustin','Sed Consequat Limited','Morbi.quis.urna@eget.net'),('Lucian','Tellus Aenean Consulting','pede.sagittis.augue@adui.co.uk'),('Ishmael','Malesuada Id Company','vel@risusNullaeget.ca'),('Xavier','Urna Convallis Consulting','molestie@In.co.uk'),('Randall','Tempor Est Ac LLP','porttitor@pharetrautpharetra.net'),('Carl','Elementum Sem Vitae Incorporated','in.sodales@musDonec.co.uk'),('Cooper','Feugiat Nec Company','sem.eget@elementumat.org'),('Xenos','Aenean Associates','Curabitur@ridiculusmusAenean.ca'),('Dylan','Ornare Ltd','Proin.velit@interdum.org'),('Reese','Et LLC','tellus.Suspendisse.sed@arcueu.edu');
INSERT INTO "categories" (name,account,mail) VALUES ('Zeph','Imperdiet Ornare LLP','ipsum.cursus.vestibulum@gravidasitamet.org'),('Peter','Consequat Lectus Sit LLP','auctor@vulputate.net'),('Tanek','Ultrices Associates','Suspendisse@nisl.co.uk'),('James','Enim Sit Amet LLP','scelerisque@ipsumnuncid.ca'),('Herman','Varius Foundation','amet@odiosagittis.edu'),('Gil','Fringilla PC','cursus.a.enim@mollis.com'),('Rogan','Sodales At Velit PC','nec.cursus.a@duiCumsociis.co.uk'),('Gannon','Erat Eget Tincidunt LLC','lobortis.mauris@pede.co.uk'),('Fletcher','Aliquet Sem Ut Incorporated','quis@tempusrisus.co.uk'),('Edan','Metus Inc.','dolor@scelerisqueloremipsum.org');
INSERT INTO "categories" (name,account,mail) VALUES ('Harding','Sed Eget Lacus Ltd','ornare@interdumfeugiat.org'),('Clinton','Ligula Nullam Feugiat Institute','In.at@libero.net'),('Bruno','Et Tristique LLC','euismod.ac.fermentum@atlibero.co.uk'),('Louis','Risus Quis Corp.','aliquam@quamCurabiturvel.com'),('Wing','Curae; Phasellus Ornare Consulting','libero.Integer@Nunc.ca'),('Dominic','Tellus Lorem Eu Consulting','tellus@risus.org'),('Harding','Eget Magna Suspendisse LLP','sodales@nondui.edu'),('Bevis','In Corporation','nec.quam.Curabitur@nequepellentesque.net'),('Walter','Ultrices Iaculis Foundation','ultricies.ligula@sed.co.uk'),('Jasper','Dolor Incorporated','aliquet@tellus.net');
INSERT INTO "categories" (name,account,mail) VALUES ('Isaac','Mollis Dui In Company','semper@ornareplaceratorci.ca'),('Scott','Nulla Facilisi Sed PC','Aliquam.auctor@ultricesmauris.net'),('Graham','Odio Semper Industries','a.magna.Lorem@lacusvestibulumlorem.co.uk'),('Orson','Curabitur Massa Consulting','blandit@massa.ca'),('Eaton','Faucibus Limited','Phasellus.fermentum@Donecat.net'),('Owen','A Corporation','pulvinar@egestasurnajusto.ca'),('Laith','Eu Incorporated','tincidunt.Donec@sedorcilobortis.co.uk'),('Colby','Ipsum Ac Incorporated','aliquet.magna@non.org'),('Walter','Sed Est PC','nonummy.Fusce@tempusmauriserat.co.uk'),('Joshua','Mauris Morbi Non Limited','Donec@primisin.net');
INSERT INTO "categories" (name,account,mail) VALUES ('Donovan','Orci Phasellus Dapibus LLP','Maecenas@montesnasceturridiculus.com'),('Dalton','Etiam Foundation','blandit.Nam@risusNulla.com'),('Tanek','Eget Lacus Corporation','fringilla.Donec@nuncullamcorper.net'),('Randall','Tellus Non Magna Inc.','tempor.bibendum.Donec@Donecconsectetuer.co.uk'),('Isaac','Sodales Foundation','blandit.Nam@Curabitur.com'),('Channing','Scelerisque Ltd','elit.dictum.eu@id.co.uk'),('Christian','Senectus Ltd','et@elit.net'),('Tanek','Enim Non Nisi Corporation','eu.augue@Cras.net'),('Todd','Donec Nibh Enim Institute','Cras.dictum@utpellentesqueeget.co.uk'),('Jasper','Donec Ltd','fringilla@etnuncQuisque.co.uk');
INSERT INTO "categories" (name,account,mail) VALUES ('Trevor','Dolor Donec Fringilla Institute','id.erat@mi.org'),('Zane','Arcu Associates','nisi@Donec.edu'),('Daquan','Amet Consectetuer Adipiscing Company','Duis.mi@sitamet.net'),('Asher','Proin Vel Corp.','quis.lectus.Nullam@atauctor.edu'),('Rooney','Litora Torquent Per PC','est.Nunc@netus.edu'),('Kasimir','Pretium Neque Morbi Company','est.tempor.bibendum@doloregestasrhoncus.co.uk'),('Drake','Sollicitudin Orci Sem Associates','montes.nascetur@elementumduiquis.edu'),('Dillon','Sodales At Foundation','Donec.egestas.Duis@nuncsed.org'),('Victor','Aliquam Ornare PC','metus@rutrummagna.co.uk'),('Ivor','Ipsum Ac Mi LLP','in.hendrerit@adipiscinglacusUt.co.uk');
INSERT INTO "categories" (name,account,mail) VALUES ('Arsenio','Hendrerit A Arcu Inc.','id.enim@augueut.com'),('Channing','Nulla Ante Iaculis Industries','ac@turpisNullaaliquet.net'),('Bert','Proin Dolor Corp.','ridiculus.mus@Vivamus.edu'),('Edward','Cursus Nunc Mauris Corp.','lorem@ligulaconsectetuerrhoncus.edu'),('Bruno','Nunc Associates','pulvinar@malesuadavel.co.uk'),('Dieter','Mauris Blandit Institute','egestas.Aliquam.nec@facilisismagna.net'),('Adam','Auctor Quis Tristique Inc.','netus.et@Donec.net'),('Nero','Vel Industries','lorem@Integeridmagna.org'),('Solomon','Felis Ullamcorper Viverra Associates','nulla.Integer@lorem.edu'),('Thomas','Sed Limited','laoreet@adipiscing.ca');
INSERT INTO "categories" (name,account,mail) VALUES ('Matthew','In Lobortis Tellus Incorporated','ultrices.Vivamus@egetlacus.edu'),('Stewart','Cras Vulputate Velit Inc.','mi@sitametfaucibus.net'),('Hammett','Suspendisse Ac Metus Associates','dictum.placerat.augue@nisiAeneaneget.com'),('Timon','Facilisis Magna Tellus Institute','Ut.tincidunt.vehicula@cursuset.org'),('Wallace','Dapibus Gravida Company','luctus@ullamcorper.co.uk'),('Caleb','Nunc Ac Mattis Company','nunc.In.at@mieleifendegestas.net'),('Xenos','Nunc Incorporated','sagittis.augue.eu@eleifend.com'),('Raymond','Dui Fusce LLP','Nullam.enim.Sed@montesnascetur.ca'),('Zeus','Nunc Quis Corporation','rutrum.non@Duis.co.uk'),('Dexter','Libero PC','Sed.auctor.odio@cursusNunc.net');
INSERT INTO "categories" (name,account,mail) VALUES ('Arden','Sit Amet Inc.','magna.Nam.ligula@quispedePraesent.co.uk'),('Stuart','Lacinia At Foundation','Cum@aliquet.net'),('Ashton','Hendrerit PC','id.nunc.interdum@urnaNullam.org'),('Fitzgerald','Nascetur Ridiculus Company','viverra@accumsan.edu'),('Hu','Mauris Corp.','posuere.cubilia.Curae@enimNunc.net'),('Tad','Quisque Imperdiet Institute','hendrerit.Donec@felisadipiscingfringilla.edu'),('Victor','Nullam Company','auctor.non.feugiat@feugiatnecdiam.net'),('Clarke','Duis Cursus LLC','ornare.elit@amagna.co.uk'),('Dieter','Donec Feugiat Institute','ac@erat.co.uk'),('Laith','Euismod Ac Fermentum LLP','vitae@orci.ca');
INSERT INTO "categories" (name,account,mail) VALUES ('Blake','Libero Est Congue PC','tincidunt.congue@sem.org'),('Fletcher','Eget Corporation','nibh.Quisque.nonummy@inconsequatenim.com'),('Basil','At Sem Molestie Industries','lorem.fringilla.ornare@nibhQuisque.com'),('Charles','Eros Proin Ultrices LLP','Morbi.vehicula.Pellentesque@ipsumporta.com'),('Cedric','Augue Malesuada Malesuada Institute','a.nunc.In@erat.net'),('Lane','Arcu LLP','sed.pede@adipiscing.co.uk'),('Hu','Scelerisque Limited','In.lorem.Donec@ettristique.com'),('Kadeem','Sed Nunc Est Ltd','sit.amet.ultricies@interdum.ca'),('Raja','Praesent Interdum Foundation','dignissim.magna@risus.net'),('Ciaran','Libero Incorporated','tincidunt@ultricesiaculis.co.uk');
